services:
  greeting-service:
    image: ghcr.io/kucukbalik/greetingservice/app:latest
    ports:
      - "8081:8081"
    networks:
      - labnet
    env_file:
      - ./.env

  proxy-service:
    image: ghcr.io/kucukbalik/greeting-proxy/app
    ports:
      - "8080:8080"
    networks:
      - labnet
    depends_on:
      - greeting-service
    env_file:
      - ./.env

networks:
  labnet:
